#pragma once

#define MAX_JOINT_COUNT 256
#define MAX_JOINT_PER_VERTEX 4

#define MAX_LIGHT_COUNT 8
#define MAX_SHADOWBOX_COUNT 2
#define MAX_SHADOWMAP_COUNT 3
const unsigned int SHADOWMAP_TEXTURE_PS_START_SLOT = 4;
#define SHADOWMAP_TEXTURE_SIZE_X 4096
#define SHADOWMAP_TEXTURE_SIZE_Y 4096
#define SHADOWMAP_TEXTURE_MIN_DIV 8